language: python

python:
  - "2.7"

install:
  - "pip install codecov"
  - "pip install -r requirements.txt"

before_script:
 - npm update -g npm
 - npm install -g grunt-cli

script:
  #coverage run tests.py
  grunt test --verbose --force


after_success:
  - codecov
