language: python

python:
  - "2.7"

install:
  - "pip install codecov"
  - "pip install -r requirements.txt"
  - "pip install nose"
  - "npm update -g npm; npm install"

script:
  - nosetests tests/tests_markdown.py tests/tests_markdown_final.py --with-coverage
  - npm run ci

after_success:
  - codecov
